### ISSUE TITLE
  failed to run the command: build irsimple jar

### ISSUE THREAD

**Issue by lczhang06** [IBM/span-selection-pretraining#1]
I tried to run this code to create the pre-training data, however I failed to run the command: build irsimple jar.  
Below is the error information:
```
Build environment: Linux-4.4.0-62-generic-x86_64-with-debian-stretch-sid
Build start time: 18:06:31, Oct.28 2019

build.py...
 : error 1005: More than one targets are not supported.
	Please select one of: all genc genmake modules libraries fds clean cleanall cleanlib run

- Failed -
Build end time: 18:06:31, Oct.28 2019
Build total time: 00:00:00
```
How could I execute this command correctly?

**Comment by michaelrglass** [comment]
I updated the instructions to be more clear. You can actually use the irsimple.jar included in the repo itself if you aren't changing the code. Otherwise "mvn clean compile assembly:single" will work.
